<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.targets" />
  <Import Project="..\SpaceShared\SpaceShared.projitems" Label="Shared" />

  <PropertyGroup>
    <Name>Angry Seagulls</Name>
    <UniqueId>spacechase0.$(AssemblyName)</UniqueId>
    <Version>1.0.1</Version>
    <TargetFramework>net6.0</TargetFramework>

    <EnableHarmony>true</EnableHarmony>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="assets\" />
  </ItemGroup>
</Project>
