<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(SolutionDir)common.targets" />
  <Import Project="$(SolutionDir)harmony.targets" />

  <PropertyGroup>
    <UniqueId>spacechase0.$(AssemblyName)</UniqueId>
    <Version>1.0.15</Version>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModTranslationClassBuilder" Version="2.0.0" />
  </ItemGroup>

  <Import Project="$(SolutionDir)spacecore.targets" /></Project>
