<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!--common project properties-->
  <PropertyGroup>
    <Authors>kittycatcasey</Authors>
    <Description>...</Description>
    <UniqueId>kittycatcasey.$(AssemblyName)</UniqueId>
    <MinimumApiVersion_Behavior>Update</MinimumApiVersion_Behavior>
    <MinimumGameVersion_Behavior>UpdateFull</MinimumGameVersion_Behavior>
    
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <LangVersion>preview</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
  </PropertyGroup>

  <!--import mod build package-->
  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.2-casey" />
    <PackageReference Include="Leclair.Stardew.ModManifestBuilder" Version="2.4.0" />
  </ItemGroup>

  <!-- Why didn't I do this for SpaceShared in the first place? -->
  <Import Project="$(SolutionDir)shared\SpaceShared.Common\SpaceShared.Common.projitems" Label="Shared" />
  <Import Project="$(SolutionDir)shared\SpaceShared.Mods.SourceGen\SpaceShared.SourceGenCommon.projitems" Label="Shared" />
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)shared\SpaceShared.SourceGenerator\SpaceShared.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <!--common mod build package options-->
  <PropertyGroup>
    <ModZipPath>$(SolutionDir)_releases</ModZipPath>
    <EnableModZip Condition="$(Configuration) != 'Release'">False</EnableModZip>
  </PropertyGroup>

  <!-- This sometimes fixes running the game from the right folder when I use an environment variable to override my game path. No idea why -->
  <!-- Other times it breaks it when it was working (which is only sometimes)! Joy -->
  <!-- Might be related to opening another instance the normal way after having already done an environment variable override, at least until next restart? -->
  <PropertyGroup Condition="'$(OS)' == 'Windows_NT'">
    <StartProgram>$(GamePath)\StardewModdingAPI.exe</StartProgram>
    <StartWorkingDirectory>$(GamePath)</StartWorkingDirectory>
  </PropertyGroup>

  <!-- mac workaround, remove when updating mod build config -->
  <PropertyGroup Condition="'$(OS)' != 'Windows_NT'">
    <StartAction>Program</StartAction>
    <StartProgram>/Users/spacechase0/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS\StardewModdingAPI</StartProgram>
    <StartWorkingDirectory>/Users/spacechase0/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS</StartWorkingDirectory>
  </PropertyGroup>
</Project>
