<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>uuid</key>
    <string>5e106ed0-2771-48ed-9597-9a84c4f3493d</string>
	<key>filestypes</key>
	<array>
		<string>spacecore</string>
	</array>
	<key>name</key>
	<string>SpaceCore Content</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#element</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>(\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>startarray</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>endarray</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.array</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array-element</string>
				</dict>
			</array>
		</dict>
		<key>array-element</key>
		<dict>
			<key>begin</key>
			<string></string>
			<key>end</key>
			<string>;|]</string>
			<key>name</key>
			<string>meta.array-element</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element</string>
				</dict>
			</array>
		</dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>startblock</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>endblock</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.block</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-element</string>
				</dict>
			</array>
		</dict>
		<key>block-element</key>
		<dict>
			<key>begin</key>
			<string>((\\.|[^\[\]\{\}\(\)\;\:\~\'\"\\\s])(\\.|[^\[\]\{\}\(\)\;\:\~\'\"\\])*):</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;|}</string>
			<key>name</key>
			<string>meta.block-element</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>name</key>
			<string>comment.spacecorecontent</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*$
?</string>
					<key>name</key>
					<string>comment.line.spacecorecontent</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.spacecorecontent</string>
				</dict>
			</array>
		</dict>
		<key>element</key>
		<dict>
			<key>name</key>
			<string>meta.element</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#funccall</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>constant.character.escape.spacecorecontent</string>
		</dict>
		<key>funccall</key>
		<dict>
			<key>begin</key>
			<string>([^\[\]\{\}\(\)\;\:\~\'\"\\\s]+)\(()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>startparen</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>endparen</string>
				</dict>
			</dict>
			<key>name</key>
			<string>funccall</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#element</string>
				</dict>
			</array>
		</dict>
		<key>quoted-strings</key>
		<dict>
			<key>begin</key>
			<string>((?!\\)("|'))</string>
			<key>end</key>
			<string>\2</string>
			<key>name</key>
			<string>string.quoted.spacecorecontent</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>raw-strings</key>
		<dict>
			<key>match</key>
			<string>[^\[\]\{\}\(\)\;\:\~\'\"\\\s]</string>
			<key>name</key>
			<string>string.raw.spacecorecontent</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>name</key>
			<string>string.spacecorecontent</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#raw-strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted-strings</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.spacecore</string>
</dict>
</plist>
