<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(SolutionDir)common.targets" />

  <PropertyGroup>
    <Name>Gradient Hair Colors</Name>
    <UniqueId>spacechase0.$(AssemblyName)</UniqueId>
    <Version>1.1.1</Version>
    <UpdateKeys>Nexus:12744</UpdateKeys>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
