<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(SolutionDir)common.targets" />
  <Import Project="$(SolutionDir)harmony.targets" />

  <PropertyGroup>
    <Name>Random Cats in Events</Name>
    <UniqueId>spacechase0.$(AssemblyName)</UniqueId>
    <Description>...</Description>
    <Version>1.1.0</Version>
    <UpdateKeys>Nexus:26444</UpdateKeys>


  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModTranslationClassBuilder" Version="2.1.0" />
  </ItemGroup>
</Project>
