<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(SolutionDir)common.targets" />
  <Import Project="$(SolutionDir)shared\SpaceShared\SpaceShared.projitems" Label="Shared" />
  <Import Project="$(SolutionDir)shared\SpaceSharedPatching\SpaceSharedPatching.projitems" Label="Shared" />

  <PropertyGroup>
    <Name>Stardew Reality</Name>
    <Description>Stardew Valley... in VIRTUAL REALITY. (Incompatibility with other mods almost guarenteed.)</Description>
    <Version>0.1.0</Version>
    
    <TargetFramework>net6.0</TargetFramework>
    
    <EnableHarmony>true</EnableHarmony>
    <BundleExtraAssemblies>ThirdParty</BundleExtraAssemblies>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenVR.NET" Version="0.8.5" IncludeAssets="all" GeneratePathProperty="true" />
    <None Include="$(PkgOpenVR_Net)/content/openvr_api.dll" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Pathoschild.Stardew.ModTranslationClassBuilder" Version="2.0.0" />
  </ItemGroup>

  <Target Name="CheckForOpenvrApi" BeforeTargets="Build">
    <Error Condition=" !Exists( '$(PkgOpenVR_Net)/content/openvr_api.dll' ) " Text="OpenVR API didn't exist in $(PkgOpenVR_Net)" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)gameplay\overhaul\Stardew3D\Stardew3D.csproj" Private="False">
      <Version_AppendConfiguration>false</Version_AppendConfiguration>
    </ProjectReference>
  </ItemGroup>
</Project>
